<?php
$base = $_ENV['APP_URL'] ?? '';
$isEdit = !empty($voucher);
$action = $isEdit ? $base . '/admin/vouchers/' . (int) $voucher['id'] . '/edit' : $base . '/admin/vouchers/create';
$datetime = static fn(?string $value): string => $value ? date('Y-m-d\TH:i', strtotime($value)) : '';
$selectedProducts = $selectedProducts ?? [];
$selectedCategories = $selectedCategories ?? [];
?>
<div class="max-w-4xl space-y-5"><div class="flex items-center gap-3"><a href="<?= $base ?>/admin/vouchers" class="text-muted text-sm">← Voucher</a><span>/</span><h1 class="text-xl font-bold"><?= $isEdit ? 'Sửa voucher' : 'Tạo voucher' ?></h1></div>
<form method="post" action="<?= $action ?>" class="bg-white border border-gray-200 rounded-xl p-6 space-y-5">
    <div class="grid sm:grid-cols-2 gap-4"><label class="text-sm">Mã voucher<?= $isEdit ? ' (không thể đổi)' : '' ?><input name="code" required <?= $isEdit ? 'readonly' : '' ?> value="<?= htmlspecialchars($voucher['code'] ?? '') ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 uppercase <?= $isEdit ? 'bg-gray-100' : '' ?>"></label><label class="text-sm">Mô tả<input name="description" value="<?= htmlspecialchars($voucher['description'] ?? '') ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label></div>
    <div class="grid sm:grid-cols-2 gap-4"><label class="text-sm">Loại giảm<select name="discount_type" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"><option value="percent" <?= ($voucher['discount_type'] ?? 'percent') === 'percent' ? 'selected' : '' ?>>Phần trăm (%)</option><option value="fixed" <?= ($voucher['discount_type'] ?? '') === 'fixed' ? 'selected' : '' ?>>Số tiền cố định</option></select></label><label class="text-sm">Giá trị giảm<input type="number" step="0.01" min="0.01" name="discount_value" required value="<?= htmlspecialchars($voucher['discount_value'] ?? '') ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label><label class="text-sm">Giảm tối đa<input type="number" step="0.01" min="0" name="max_discount_amount" value="<?= htmlspecialchars($voucher['max_discount_amount'] ?? '') ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label><label class="text-sm">Đơn tối thiểu<input type="number" step="0.01" min="0" name="min_order_value" value="<?= htmlspecialchars($voucher['min_order_value'] ?? 0) ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label></div>
    <div class="grid sm:grid-cols-2 gap-4"><label class="text-sm">Bắt đầu<input type="datetime-local" name="start_date" required value="<?= $datetime($voucher['start_date'] ?? null) ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label><label class="text-sm">Kết thúc<input type="datetime-local" name="end_date" required value="<?= $datetime($voucher['end_date'] ?? null) ?>" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label><label class="text-sm">Tổng lượt dùng<input type="number" min="1" name="usage_limit" value="<?= htmlspecialchars($voucher['usage_limit'] ?? '') ?>" placeholder="Để trống = không giới hạn" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label><label class="text-sm">Lượt dùng mỗi user<input type="number" min="1" name="usage_limit_per_user" value="<?= htmlspecialchars($voucher['usage_limit_per_user'] ?? '') ?>" placeholder="Để trống = không giới hạn" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"></label></div>
    <div class="grid sm:grid-cols-2 gap-4"><label class="text-sm">Sản phẩm áp dụng<select name="product_ids[]" multiple size="7" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"><?php foreach ($products as $product): ?><option value="<?= (int) $product['id'] ?>" <?= in_array($product['id'], $selectedProducts) ? 'selected' : '' ?>><?= htmlspecialchars($product['name']) ?></option><?php endforeach; ?></select></label><label class="text-sm">Danh mục áp dụng<select name="category_ids[]" multiple size="7" class="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2"><?php foreach ($categories as $category): ?><option value="<?= (int) $category['id'] ?>" <?= in_array($category['id'], $selectedCategories) ? 'selected' : '' ?>><?= htmlspecialchars($category['name']) ?></option><?php endforeach; ?></select><span class="block text-xs text-muted mt-1">Để trống cả hai để áp dụng toàn shop.</span></label></div>
    <label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" <?= (!$isEdit || !empty($voucher['is_active'])) ? 'checked' : '' ?>> Kích hoạt voucher</label>
    <div class="pt-4 border-t border-gray-100 flex justify-end gap-3"><a href="<?= $base ?>/admin/vouchers" class="px-4 py-2 text-sm">Hủy</a><button class="bg-charcoal text-white rounded-lg px-5 py-2 text-sm">Lưu voucher</button></div>
</form></div>
